# Generated by Django 3.2.16 on 2022-12-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voicesearch',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='voicesearch',
            old_name='Part_Name',
            new_name='part_name',
        ),
        migrations.RenameField(
            model_name='voicesearch',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
